server:
  port: 8080

# Default connection pool
spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

# Database
    url: jdbc:postgresql://localhost:5432/dev
    username: postgres
    password: postgres

# Default Schema
  flyway:
    schemas: users
  jpa:
    properties:
      hibernate:
        default_schema: users
